In [6]:
a = "the sky is blue"
a_ = a.split()
a_

['the', 'sky', 'is', 'blue']

In [13]:
n = len(a_)
for i in range(n//2):
    j = n-i-1
    a_[i], a_[j] = a_[j], a_[i]

In [19]:
" ".join(word for word in a_)

'blue is sky the'

In [18]:
A = "Hello World"
print(A)
' '.join(A.strip().split(' ')[::-1])

Hello World


'World Hello'

In [5]:
for i in range(3+1):
    print(11**i)

1
11
121
1331


In [8]:
p = 11**3

In [10]:
p = list(str(p))

In [1]:
11**5

161051

In [2]:
word_dic = {}
s = "abccccdd"
for ch in s:
    if ch not in word_dic:
        word_dic[ch] = 1
    else:
        word_dic[ch] += 1
word_dic

{'a': 1, 'b': 1, 'c': 4, 'd': 2}

In [3]:
word_dic['a']

1

In [5]:
s = 'bb'
word_dic = {}
for ch in s:
    if ch not in word_dic:
        word_dic[ch] = 1
    else:
        word_dic[ch] += 1
odd = 0
for key, value in word_dic.items():
    odd += word_dic[key]%2
print(len(s)-odd+1 if odd > 0 else len(s))

2


In [4]:
"b" > "a"

True

In [10]:
grid = ['ebacd', 'fghij', 'olmkn', 'trpqs', 'xywuv']
for i in range(len(grid)):
    grid[i] = list(grid[i])
    grid[i].sort()
grid

[['a', 'b', 'c', 'd', 'e'],
 ['f', 'g', 'h', 'i', 'j'],
 ['k', 'l', 'm', 'n', 'o'],
 ['p', 'q', 'r', 's', 't'],
 ['u', 'v', 'w', 'x', 'y']]

In [6]:
"acbda".sort()

AttributeError: 'str' object has no attribute 'sort'

In [16]:
a = "   a ci f ved pu vkfzbu bnbvlvgkua imjd hrrnx nopp p kso iejgcd wyalgcxie yfslfzzw lygatpbv wr budfobxsm   "
print(Solution().solve(a))

In [2]:
a.strip()

'a ci f ved pu vkfzbu bnbvlvgkua imjd hrrnx nopp p kso iejgcd wyalgcxie yfslfzzw lygatpbv wr budfobxsm'

In [13]:
class Solution:
    # @param A : string
    # @return a strings
    def reverse(self,A,s,e):
        while s<e:
            A[s],A[e] = A[e],A[s]
            s += 1
            e -= 1
        return A
            

    def solve(self, A):
        A = list(A)
        A = self.reverse(A,0,len(A)-1)
        A.append(" ")
        i,j =0,0
        while j<len(A):
            while A[j] != " ":
                j += 1
            
            A = self.reverse(A,i,j-1)
            j += 1
            i = j
        
        A = "".join(A)
        return A.strip()

In [17]:
print(Solution().solve(a))

budfobxsm wr lygatpbv yfslfzzw wyalgcxie iejgcd kso p nopp hrrnx imjd bnbvlvgkua vkfzbu pu ved f ci a


In [15]:
class Solution:
    # @param A : string
    # @return a strings
    def reverse(self,A,s,e):
        while s<e:
            A[s],A[e] = A[e],A[s]
            s += 1
            e -= 1
        return A
    def strip(self, A):
        for i in range(len(A)):
            if A[i] != " ":
                A = A[i:]
                break 
        for i in range(len(A)-1,-1,-1):
            if A[i] != " ":
                A = A[:i+1]
                break
        return A     

    def solve(self, A):
        A = list(A)
        A = self.reverse(A,0,len(A)-1)
        A.append(" ")
        i,j =0,0
        while j<len(A):
            while A[j] != " ":
                j += 1
            
            A = self.reverse(A,i,j-1)
            j += 1
            i = j
        
        A = "".join(A)
        A = self.strip(A)
        return A

In [ ]:
def prefixSum(self,A,B):
        aux = []
        curr = sum(A[:B])
        aux.append(curr)
        for i in range(B, len(A)):
            curr = curr+A[i]-A[i-B]
            aux.append(curr)
        return aux

print(prefixSum([1,2,3,4,5], 3))

In [6]:

first_row = "qwertyuiop"
second_row = "asdfghjkl"
third_row = "zxcvbnm"
cat_dic = {}
cat_no = 0
for i in range(97, 123):
    if chr(i) in first_row: cat_no = 1 
    elif chr(i) in second_row: cat_no = 2
    else: cat_no = 3
    cat_dic[chr(i)] = cat_no
cat_dic

{'a': 2,
 'b': 3,
 'c': 3,
 'd': 2,
 'e': 1,
 'f': 2,
 'g': 2,
 'h': 2,
 'i': 1,
 'j': 2,
 'k': 2,
 'l': 2,
 'm': 3,
 'n': 3,
 'o': 1,
 'p': 1,
 'q': 1,
 'r': 1,
 's': 2,
 't': 1,
 'u': 1,
 'v': 3,
 'w': 1,
 'x': 3,
 'y': 1,
 'z': 3}

In [8]:
words = ["Hello","Alaska","Dad","Peace"]
words = words[0].lower()
words

'hello'

In [22]:
class Solution(object):
    def categoryDic(self):
        cat_dic = {}
        cat_no = 0
        for i in range(97, 123):
            if chr(i) in "qwertyuiop": cat_no = 1 
            elif chr(i) in "asdfghjkl": cat_no = 2
            elif chr(i) in "zxcvbnm": cat_no = 3
            cat_dic[chr(i)] = cat_no
    def findWords(self, words):
        cat_dic = self.categoryDic()
        ans = []
        for word in words:
            word = word.lower()
            cnt = set()
            for ch in word:
                cnt.add(cat_dic[ch])
            if len(cnt) == 1:
                ans.append(word)
        return ans
words = ["Hello","Alaska","Dad","Peace"]
print(Solution().findWords(words))
print(Solution().categoryDic())

TypeError: 'NoneType' object is not subscriptable

In [13]:
count = set()
count.add(1)

In [1]:
import numpy as np

In [14]:
array = np.random.randint(1, 101, size=(5,5))

In [15]:
array[array > 50 and array < 80]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [8]:
array[array != 0]=1

In [18]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [19]:
a*a

array([ 0,  1,  4,  9, 16])

In [20]:
np.vectorize(np.square)(a)

array([ 0,  1,  4,  9, 16])

In [22]:
np.array([i*i for i in a])

array([ 0,  1,  4,  9, 16])

In [29]:
arr = list(range(0, 10))
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
even = []
odd = []
for n in arr:
    if n % 2 == 0:
        even.append(n)
    else:
        odd.append(n)
even, odd


AttributeError: 'list' object has no attribute 'mean'

In [35]:
even.sum()

AttributeError: 'list' object has no attribute 'sum'

In [38]:
(sum(even))/5

4.0

In [1]:
class Football:
  final_res = "lose"
  def __init__(self, name, score):
    self.name = name
    self.score = score
    self.final_res = "lose"
  def calc(self, winning_score):
    if self.score > winning_score:
       self.final_res = "win"

match = Football("Juventus", 3)
match.calc(2)
print(Football.final_res, match.final_res)

lose win


In [4]:
class NewClass:
    print("Hello World")

NewClass()


Hello World


In [5]:

A = NewClass()


In [6]:
B = NewClass

In [7]:

NewClass()

In [1]:
def bar(x,y):
    if y == 0:
        return 0
    return (x+bar(x, y-1))

def foo(x, y):
    if y == 0:
        return 1
    return bar(x, foo(x, y-1))

print(foo(3, 5))

243


In [2]:
def fun(x, n):
    if (n == 0):
        return 1
    elif n%2==0:
        return fun(x*x, n//2)
    else:
        return x*fun(x*x, (n-1)//2)

print(fun(2, 10))

1024
