In [2]:
import pandas as pd
import numpy as np

Uni-variate Analysis - Need only 1 Columns to answer the question such as:
> 1. Average Step count per day <br>
> 2. Highest and lowest step count. <br> 
<br>


Bi-Variate Analysis - Where we use 2 feature to answer the question such as:
> 1. what is the mood if our colories burned is this much. <br>
> 2. what is the mood if our step coutn is heigher or lower.

Multi-Variate Analysis - if More then 2 feature is involve to solve the question is called multivariant analysis.

In [34]:
a = [1,2,3,4,5]
a_sq = [elm**2 for elm in a]
a_sq, a

([1, 4, 9, 16, 25], [1, 2, 3, 4, 5])

In [35]:
np_arr = np.array(a)
np_sq = np_arr**2
np_sq, np_arr

(array([ 1,  4,  9, 16, 25]), array([1, 2, 3, 4, 5]))

Check Time to execute:
> if you have perform element Wise operation, numpy provides you. <br>
> 1. Clean Syntax <br>
> 2. Computation Benefit

In [36]:
l = range(1000000)
%timeit [i**2 for i in l]

345 ms ± 70.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [37]:
np_ar = np.arange(1000000)
%timeit np_ar**2

2.74 ms ± 197 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


ndim & shape

In [38]:
np_arr = np.array([1,2,3,4,5,6])
print(np_arr.ndim, np_arr.shape)

1 (6,)


arange

In [39]:
print(np.arange(5))
print(np.arange(1,5))
print(np.arange(1,5,2))
print(np.arange(1,5,0.5))

[0 1 2 3 4]
[1 2 3 4]
[1 3]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


linespace - end point also inclueded

In [40]:
np.linspace(0,100,12)

array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ])

Q. Why it is call numpy array not list?
> 1. because it is written in C. it return the array not list. <br
> 2. Homegenious element store.

In [41]:
arr2 = np.array([1,2,3,4])
print(arr2)

[1 2 3 4]


In [42]:
arr3 = np.array([1,2,3,4], dtype='float')
print(arr3)

[1. 2. 3. 4.]


In [43]:
arr4 = np.array([1,2.2,'vishal']) #convert everything to string
arr4

array(['1', '2.2', 'vishal'], dtype='<U32')

Special Metrix
> Zeros, Ones, diag, identity

In [44]:
np.zeros(3)

array([0., 0., 0.])

In [45]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.ones((2,3))*5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [47]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [48]:
a = np.diag([1,2,3])
np.diag(a)

array([1, 2, 3])

In [49]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
arr6 = np.array([[1,2,3,4],[5,6,7,8]])
arr6


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
arr6.ndim, arr6.shape, len(arr6)

(2, (2, 4), 2)

In [52]:
arr = np.array([1,2,3,4,5,6,7,8], ndmin = 2)
arr #row vector

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [53]:
arr.ndim, arr.shape, len(arr)

(2, (1, 8), 1)

Create a metrix using arange

In [54]:
lst = np.arange(1,13)
print(lst)
arr.ndim, arr.shape, len(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


(2, (1, 8), 1)

Reshape Function

In [55]:
lst.reshape(3,4), lst.reshape(4,3)

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]))

In [56]:
lst.reshape(12,1), lst.reshape(1,12)

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]]),
 array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]))

In [57]:
lst.reshape(6,-1) # -1 automatically change shape

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [58]:
lst.reshape(-1,6) # -1 automatically change shape

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Resize function 

In [59]:
import numpy as np
a = np.arange(5)
a.resize(2,4)  #fill o if value exceded
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0]])

In [60]:
a = np.arange(5)
b = np.resize(a,(2,4))  #fill o if value exceded
b

array([[0, 1, 2, 3],
       [4, 0, 1, 2]])

In [61]:
a = np.arange(4)
c = a
a.resize(2,4) #can not resize because it is refer by another varible.

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

Transpose Metrix
> Transpose can only be applicatable using 2d vector, not 1d vector.

In [62]:
a = np.arange(4).reshape(1,4)
a.T #converted to column vector

array([[0],
       [1],
       [2],
       [3]])

In [63]:
a = np.arange(4) #didn't change because it is 1d vector
a.T

array([0, 1, 2, 3])

Flattern Array
>convert the 2d array in 1d array

In [64]:
ar = np.arange(12).reshape(3,4)
print(ar)
ar.flatten()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
ar.reshape(12)
# (1,12)- make it row vector
# (12,1) - make it column vector
# 12 - only single value can make flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Indexing and Sliceing

In [66]:
m1 = np.arange(1,10).reshape(3,3)
print(m1)
print(m1[1][2]) #python syntax
print(m1[1,2]) #Numpy syntax- use this syntex only

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
6


In [67]:
#multiple index accessing 1D-Array
m = np.array([100,200,300,400,500,600])
m[[1,2,1,1,5,2]]

array([200, 300, 200, 200, 600, 300])

In [68]:
#multiple index accessing 2D-Array
m1 = np.arange(1,10).reshape(3,3)
m1[[0,0,1],[0,1,2]]

array([1, 2, 6])

In [69]:
ar = np.arange(12)
print(ar)
print(ar[:5])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4]


In [70]:
ar = np.arange(12).reshape(3,4)
print(ar)
print(ar[0,1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2]


In [71]:
ar[:, 2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [72]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])
a[2:5] = b[::-1]

In [73]:
a

array([1, 2, 6, 7, 8])

Fancy Indexing

In [75]:
m1 = np.arange(12).reshape(3,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
m1[m1>6] #mask

array([ 7,  8,  9, 10, 11])

In [5]:
a = np.arange(11)
a[(a%2==0) | (a%5==5)]

array([ 0,  2,  4,  6,  8, 10])

In [6]:
a=np.arange(6)
mask = (a%2==0)
a[mask] = -1
a

array([-1,  1, -1,  3, -1,  5])

## Lecture 2

Universal Function(Ufunct)
> 1. Vectorised Functions
> 2. Aggregate Functions/Reduction Functions
> 3. Logical Functions

In [9]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
print(a+b) #internally runs below function
print(np.add(a,b))


[ 5  7  9 11]
[ 5  7  9 11]


In [13]:
a = np.arange(12).reshape(3,4)
print(a)
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]


In [16]:
print(np.mean(a))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]


In [18]:
print(np.min(a))
print(np.min(a, axis=0))
print(np.min(a, axis=1))

0
[0 1 2 3]
[0 4 8]


Logical Function:
>**Any Function**: if there is any non zero element then I'll get True else I'll get False.

In [22]:
a = np.array([1,2,3,4])
np.any(a)

True

In [20]:
a = np.array([1,0,1,0])
np.any(a)

True

In [21]:
a = np.array([0,0,0,0])
np.any(a)

False

In [26]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
mask = a<b
print(np.any(mask))
print(np.all(mask))

True
False


In [27]:
a = np.array([5,3,3,4])
b = np.array([4,3,2,1])
mask = a<b
print(np.any(mask))
print(np.all(mask))

False
False


In [30]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
c = np.array([6,4,4,5])
mask = ((a<=b) & (b<=c))
print(np.any(mask))
print(np.all(mask))

True
False


### Sorting 

In [32]:
a = np.array([2,30,41,7,17,52])
np.sort(a)

array([ 2,  7, 17, 30, 41, 52])

In [35]:
np.argsort(a) #return the index of array in sorted order

array([0, 3, 4, 1, 2, 5], dtype=int64)

In [40]:
#if axis is not given then it is sorted as last dimension(i.e, 1)
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])
print(a)
np.sort(a)


[[ 23   4  43]
 [ 12  89   3]
 [ 69 420   0]]


array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

In [42]:
data = np.loadtxt("fitness.txt", dtype='str')
print(data.ndim)
data

2


array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65'],
       ['16-10-2017', '3148', '100', '101', '8', '0', '65'],
       ['17-10-2017', '4687', '100', '152', '5', '0', '65'],
       ['18-10-2017', '4732', '300', '150', '6', '500', '65'],
       ['19-10-2017', '3519', '100', '113', '7', '0', '65'],
       ['20-10-2017', '1580', '100', '49', '5', '0', '65'],
       ['21-10-2017', '2822', '100', '86', '6', '0', '65'],
       ['22-10-2017', '181', '10

In [43]:
data.shape

(96, 7)

In [49]:
data[0] #return first row
data.T[0], data.T[1]

(array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [50]:
#List get unpack and assign to corresponding variable
date, step_count, mood, calories_burned, hours_of_sleep, activity_status, weight = data.T

In [53]:
step_count = np.array(step_count, dtype='int')
hours_of_sleep = np.array(hours_of_sleep, dtype='int')
weight = np.array(weight, dtype='int')

In [55]:
print(mood) #it is the categorial data
print(np.unique(mood))

['200' '100' '100' '100' '200' '100' '100' '100' '100' '100' '100' '100'
 '300' '100' '100' '100' '100' '200' '200' '200' '200' '200' '200' '300'
 '200' '300' '300' '300' '300' '300' '300' '300' '200' '300' '300' '300'
 '300' '300' '300' '300' '300' '300' '300' '200' '300' '300' '300' '300'
 '300' '300' '300' '300' '300' '200' '100' '300' '300' '300' '300' '300'
 '300' '300' '100' '200' '200' '100' '100' '200' '200' '300' '200' '200'
 '100' '200' '100' '200' '200' '100' '100' '100' '100' '300' '200' '300'
 '200' '100' '100' '100' '200' '200' '100' '100' '300' '200' '200' '300']
['100' '200' '300']


> Data Munging, Data Manipulation, Data Cleaning

In [59]:
#100--> sad, 200--->Neutral, 300-->Happy
mood[mood=='100']='sad'
mood[mood=='200']='Neutral'
mood[mood=='300']='Happy'
mood

array(['Neutral', 'sad', 'sad', 'sad', 'Neutral', 'sad', 'sad', 'sad',
       'sad', 'sad', 'sad', 'sad', 'Happy', 'sad', 'sad', 'sad', 'sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'sad', 'Neutral', 'Neutral',
       'sad', 'sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'sad', 'Neutral', 'sad', 'Neutral', 'Neutral', 'sad', 'sad', 'sad',
       'sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'sad', 'sad', 'sad',
       'Neutral', 'Neutral', 'sad', 'sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')